"""
database package – Dedicated Database Layer for Vyapaar Vikash.
Contains models, schema creation, database seeding, and queries.
"""

from .models import (
    DATABASE_PATH,
    get_db,
    init_db,
    SCHEMA,
    # User operations
    create_user,
    get_user_by_email,
    get_user_by_id,
    get_user_by_google_id,
    update_user_profile,
    update_last_login,
    upsert_google_user,
    # Analysis & Certification
    save_complete_analysis,
    get_analysis_record,
    get_all_analyses,
    delete_analysis,
    get_certified_report_by_certificate_no,
    generate_certificate_number,
    generate_verification_hash,
    # Schemes & Stats
    get_all_schemes,
    get_platform_stats,
    row_to_dict,
    # Geo locations & Intelligence
    get_all_states,
    get_districts_by_state,
    get_sub_areas,
    search_geo_locations,
    get_micro_geo_intelligence,
    # Saved locations & opportunities
    save_location,
    get_saved_locations,
    delete_saved_location,
    save_opportunity,
    get_saved_opportunities,
    delete_saved_opportunity,
    # Business plans & Scenarios
    save_business_plan,
    get_business_plans,
    get_business_plan_by_id,
    delete_business_plan,
    save_location_analysis,
    get_location_analysis_by_id,
    get_all_location_analyses,
    delete_location_analysis,
    save_scenario_run,
    get_scenario_runs
)

__all__ = [
    "DATABASE_PATH",
    "get_db",
    "init_db",
    "SCHEMA",
    "create_user",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_by_google_id",
    "update_user_profile",
    "update_last_login",
    "upsert_google_user",
    "save_complete_analysis",
    "get_analysis_record",
    "get_all_analyses",
    "delete_analysis",
    "get_certified_report_by_certificate_no",
    "generate_certificate_number",
    "generate_verification_hash",
    "get_all_schemes",
    "get_platform_stats",
    "row_to_dict",
    "get_all_states",
    "get_districts_by_state",
    "get_sub_areas",
    "search_geo_locations",
    "get_micro_geo_intelligence",
    "save_location",
    "get_saved_locations",
    "delete_saved_location",
    "save_opportunity",
    "get_saved_opportunities",
    "delete_saved_opportunity",
    "save_business_plan",
    "get_business_plans",
    "get_business_plan_by_id",
    "delete_business_plan",
    "save_location_analysis",
    "get_location_analysis_by_id",
    "get_all_location_analyses",
    "delete_location_analysis",
    "save_scenario_run",
    "get_scenario_runs"
]
